"use client";

import { useResumeStore } from "@/hooks/use-resume-store";
import { Mail, Phone, Globe, MapPin } from "lucide-react";

export default function ResumePreview() {
  const { resume } = useResumeStore();

  if (!resume) {
    return (
      <div className="h-full flex items-center justify-center text-on-surface-variant/30 italic font-medium">
        Enter data to see preview
      </div>
    );
  }

  const { basics, work, education, skills, projects } = resume;

  return (
    <div className="bg-white text-stone-900 w-full min-h-full p-12 shadow-2xl space-y-8 font-sans selection:bg-indigo-100">
      {/* Header */}
      <header className="space-y-4 border-b pb-8">
        <h1 className="text-4xl font-black tracking-tight uppercase text-indigo-950">{basics.name || "Your Name"}</h1>
        <p className="text-xl font-bold text-indigo-600">{basics.label || "Professional Title"}</p>
        
        <div className="flex flex-wrap gap-4 text-sm font-medium text-stone-500 pt-2">
          {basics.email && (
            <div className="flex items-center gap-1.5">
              <Mail className="w-3.5 h-3.5" /> {basics.email}
            </div>
          )}
          {basics.phone && (
            <div className="flex items-center gap-1.5">
              <Phone className="w-3.5 h-3.5" /> {basics.phone}
            </div>
          )}
          {basics.url && (
            <div className="flex items-center gap-1.5">
              <Globe className="w-3.5 h-3.5" /> {basics.url.replace(/^https?:\/\//, '')}
            </div>
          )}
          {(basics.location.city || basics.location.region) && (
            <div className="flex items-center gap-1.5">
              <MapPin className="w-3.5 h-3.5" /> {basics.location.city}{basics.location.city && basics.location.region ? ', ' : ''}{basics.location.region}
            </div>
          )}
        </div>
      </header>

      {/* Summary */}
      {basics.summary && (
        <section className="space-y-3">
          <h2 className="text-xs font-black uppercase tracking-widest text-indigo-900 border-l-4 border-indigo-500 pl-3">Professional Summary</h2>
          <p className="text-sm leading-relaxed text-stone-600 font-medium">{basics.summary}</p>
        </section>
      )}

      {/* Experience */}
      {work.length > 0 && (
        <section className="space-y-6">
          <h2 className="text-xs font-black uppercase tracking-widest text-indigo-900 border-l-4 border-indigo-500 pl-3">Professional Experience</h2>
          <div className="space-y-6">
            {work.map((item, idx) => (
              <div key={idx} className="space-y-2">
                <div className="flex justify-between items-start">
                  <div>
                    <h3 className="font-black text-stone-800">{item.position}</h3>
                    <p className="text-sm font-bold text-indigo-600">{item.name}</p>
                  </div>
                  <p className="text-[10px] font-black uppercase text-stone-400">{item.startDate} — {item.endDate || "Present"}</p>
                </div>
                <ul className="list-disc list-outside ml-4 space-y-1.5">
                  {item.highlights.filter(h => h.trim()).map((h, i) => (
                    <li key={i} className="text-sm text-stone-600 leading-relaxed pl-1">{h}</li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </section>
      )}

      {/* Footer / Meta */}
      <div className="pt-12 text-center">
         <p className="text-[8px] font-black uppercase tracking-widest text-stone-300">Generated by DBE OS AI Forge • JSON Resume v1.0</p>
      </div>
    </div>
  );
}
